# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    param_fetcher_listener:  true
    view:
        view_response_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    exception:
        enabled: true
        exception_controller: 'App\Controller\ExceptionController::showAction'
    serializer:
        groups: ['Default']
    versioning:
        enabled: true
        default_version: v1
        resolvers:
            query:
                enabled: true
                parameter_name: version
    format_listener:
        enabled: true
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html ] }
            - { path: ^/api/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
